### ISSUE TITLE
error: uncaughtException: Maximum call stack size exceeded with node v4.0.0

### ISSUE THREAD

**Issue by varunavashia** [mongoosastic/mongoosastic#101]
While trying to start my project with node v4.0.0 I got following trace...
Commenting out the if condition in 'Log.prototype.listenerCount' under lib/log.js seems to fix this.

Version Info:
node: v4.0.0
mongoose: 4.1.1
elasticsearch: 1.7.1
mongoosastic: 3.1.4
OS: Fedora 20 (kernel 3.16.6-200.fc20.x86_64)

error: uncaughtException: Maximum call stack size exceeded date=Thu Sep 10 2015 12:45:53 GMT+0530 (IST), pid=5014, uid=1000, gid=1000, cwd=USRHOME/node-v4.0.0-linux-x64/bin, execPath=USRHOME/node-v4.0.0-linux-x64/bin/node, version=v4.0.0, argv=[USRHOME/node-v4.0.0-linux-x64/bin/node, PROJFOLDER/server/server.js], rss=78327808, heapTotal=60836096, heapUsed=39835680, loadavg=[1.5732421875, 1.3828125, 1.3642578125], uptime=3833, trace=[column=40, file=USRHOME/gitrepos/unoBridge/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js, function=Log.listenerCount, line=65, method=listenerCount, native=false, column=20, file=events.js, function=Function.EventEmitter.listenerCount, line=399, method=EventEmitter.listenerCount, native=false, column=25, file=USRHOME/gitrepos/unoBridge/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js, function=Log.listenerCount, line=68, method=listenerCount, native=false, column=20, file=events.js, function=Function.EventEmitter.listenerCount, line=399, method=EventEmitter.listenerCount, native=false, column=25, file=USRHOME/gitrepos/unoBridge/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js, function=Log.listenerCount, line=68, method=listenerCount, native=false, column=20, file=events.js, function=Function.EventEmitter.listenerCount, line=399, method=EventEmitter.listenerCount, native=false, column=25, file=USRHOME/gitrepos/unoBridge/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js, function=Log.listenerCount, line=68, method=listenerCount, native=false, column=20, file=events.js, function=Function.EventEmitter.listenerCount, line=399, method=EventEmitter.listenerCount, native=false, column=25, file=USRHOME/gitrepos/unoBridge/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js, function=Log.listenerCount, line=68, method=listenerCount, native=false, column=20, file=events.js, function=Function.EventEmitter.listenerCount, line=399, method=EventEmitter.listenerCount, native=false, column=25, file=USRHOME/gitrepos/unoBridge/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js, function=Log.listenerCount, line=68, method=listenerCount, native=false, column=20, file=events.js, function=Function.EventEmitter.listenerCount, line=399, method=EventEmitter.listenerCount, native=false, column=25, file=USRHOME/gitrepos/unoBridge/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js, function=Log.listenerCount, line=68, method=listenerCount, native=false, column=20, file=events.js, function=Function.EventEmitter.listenerCount, line=399, method=EventEmitter.listenerCount, native=false, column=25, file=USRHOME/gitrepos/unoBridge/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js, function=Log.listenerCount, line=68, method=listenerCount, native=false, column=20, file=events.js, function=Function.EventEmitter.listenerCount, line=399, method=EventEmitter.listenerCount, native=false, column=25, file=USRHOME/gitrepos/unoBridge/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js, function=Log.listenerCount, line=68, method=listenerCount, native=false, column=20, file=events.js, function=Function.EventEmitter.listenerCount, line=399, method=EventEmitter.listenerCount, native=false, column=25, file=USRHOME/gitrepos/unoBridge/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js, function=Log.listenerCount, line=68, method=listenerCount, native=false, column=20, file=events.js, function=Function.EventEmitter.listenerCount, line=399, method=EventEmitter.listenerCount, native=false, column=25, file=USRHOME/gitrepos/unoBridge/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js, function=Log.listenerCount, line=68, method=listenerCount, native=false, column=20, file=events.js, function=Function.EventEmitter.listenerCount, line=399, method=EventEmitter.listenerCount, native=false], stack=[RangeError: Maximum call stack size exceeded,

at Log.listenerCount (PROJFOLDER/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js:65:40),
at Function.EventEmitter.listenerCount (events.js:399:20),
at Log.listenerCount (PROJFOLDER/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js:68:25),
at Function.EventEmitter.listenerCount (events.js:399:20),
at Log.listenerCount (PROJFOLDER/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js:68:25),
at Function.EventEmitter.listenerCount (events.js:399:20),
at Log.listenerCount (PROJFOLDER/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js:68:25),
at Function.EventEmitter.listenerCount (events.js:399:20),
at Log.listenerCount (PROJFOLDER/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js:68:25),
at Function.EventEmitter.listenerCount (events.js:399:20),
at Log.listenerCount (PROJFOLDER/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js:68:25),
at Function.EventEmitter.listenerCount (events.js:399:20),
at Log.listenerCount (PROJFOLDER/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js:68:25),
at Function.EventEmitter.listenerCount (events.js:399:20),
at Log.listenerCount (PROJFOLDER/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js:68:25),
at Function.EventEmitter.listenerCount (events.js:399:20),
at Log.listenerCount (PROJFOLDER/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js:68:25),
at Function.EventEmitter.listenerCount (events.js:399:20),
at Log.listenerCount (PROJFOLDER/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js:68:25),
at Function.EventEmitter.listenerCount (events.js:399:20),
at Log.listenerCount (PROJFOLDER/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/log.js:68:25),
at Function.EventEmitter.listenerCount (events.js:399:20)]

**Comment by guumaster** [comment]
We've updated our dependencies to fix a similar error for io.js. Could you try mongoosastic@^3.2.0 and see if your project runs?

**Comment by varunavashia** [comment]
Works with 3.2.0.

Thanks,
Varun

**Comment by guumaster** [comment]
so we are compatible with Node v4! :+1:

**Comment by gdiab** [comment]
I'm having the same issue as OP with the following versions

Version Info:
node: v4.0.0
mongoose: 4.6.8
elasticsearch: 8.2.0
mongoosastic: 3.2.0
OS: OSX 10.12.2

**Comment by isayme** [comment]
@gdiab please upgrade your node version, see https://github.com/elastic/elasticsearch-js/issues/265
