### ISSUE TITLE
Issues with ES 2.0 ?

### ISSUE THREAD

**Issue by Alexandre-io** [mongoosastic/mongoosastic#119]
```
  8 failing

  1) Count should count a type:

      Uncaught AssertionError: expected 0 to equal 1
      + expected - actual

      -0
      +1
      
      at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
      at Assertion.prop.value (node_modules/should/lib/assertion.js:65:17)
      at test/count-test.js:61:28
      at respond (node_modules/elasticsearch/src/lib/transport.js:277:9)
      at checkRespForFailure (node_modules/elasticsearch/src/lib/transport.js:219:7)
      at HttpConnector.<anonymous> (node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
      at IncomingMessage.wrapper (node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
      at endReadableNT (_stream_readable.js:903:12)

  2) GeoTest should be able to resync geo coordinates from the database:

      Uncaught AssertionError: expected 1 to equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
      at Assertion.prop.value (node_modules/should/lib/assertion.js:65:17)
      at test/geo-test.js:135:37
      at searchCb (lib/mongoosastic.js:9:23566)
      at respond (node_modules/elasticsearch/src/lib/transport.js:277:9)
      at checkRespForFailure (node_modules/elasticsearch/src/lib/transport.js:219:7)
      at HttpConnector.<anonymous> (node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
      at IncomingMessage.wrapper (node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
      at endReadableNT (_stream_readable.js:903:12)

  3) GeoTest should be able to search points inside frames:

      Uncaught AssertionError: expected 0 to equal 1
      + expected - actual

      -0
      +1
      
      at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
      at Assertion.prop.value (node_modules/should/lib/assertion.js:65:17)
      at test/geo-test.js:173:34
      at searchCb (lib/mongoosastic.js:9:23566)
      at respond (node_modules/elasticsearch/src/lib/transport.js:277:9)
      at checkRespForFailure (node_modules/elasticsearch/src/lib/transport.js:219:7)
      at HttpConnector.<anonymous> (node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
      at IncomingMessage.wrapper (node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
      at endReadableNT (_stream_readable.js:903:12)

  4) indexing Default plugin should report errors:
     Uncaught AssertionError: expected '[query_parsing_exception] [_na] query malformed, no field after start_object, with: {"index":"tweets","line":1,"col":11}' to match /SearchPhaseExecutionException/
      at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
      at Assertion.prop.value [as match] (node_modules/should/lib/assertion.js:65:17)
      at test/index-test.js:197:28
      at searchCb (lib/mongoosastic.js:9:23152)
      at respond (node_modules/elasticsearch/src/lib/transport.js:275:9)
      at checkRespForFailure (node_modules/elasticsearch/src/lib/transport.js:219:7)
      at HttpConnector.<anonymous> (node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
      at IncomingMessage.wrapper (node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
      at endReadableNT (_stream_readable.js:903:12)

  5) Suggesters Testing Suggest should index property name with type completion:

      Uncaught AssertionError: expected 'string' to equal 'completion'
      + expected - actual

      -string
      +completion
      
      at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
      at Assertion.prop.value (node_modules/should/lib/assertion.js:65:17)
      at test/suggesters-test.js:73:34
      at respond (node_modules/elasticsearch/src/lib/transport.js:277:9)
      at checkRespForFailure (node_modules/elasticsearch/src/lib/transport.js:219:7)
      at HttpConnector.<anonymous> (node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
      at IncomingMessage.wrapper (node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
      at endReadableNT (_stream_readable.js:903:12)

  6) Suggesters Testing Suggest should return suggestions after hits:
     Uncaught TypeError: Cannot read property 'should' of undefined
      at test/suggesters-test.js:91:12
      at searchCb (lib/mongoosastic.js:9:23152)
      at respond (node_modules/elasticsearch/src/lib/transport.js:275:9)
      at checkRespForFailure (node_modules/elasticsearch/src/lib/transport.js:219:7)
      at HttpConnector.<anonymous> (node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
      at IncomingMessage.wrapper (node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
      at endReadableNT (_stream_readable.js:903:12)

  7) Synchronize existing collection should index all existing objects:

      Uncaught AssertionError: expected 1 to equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
      at Assertion.prop.value (node_modules/should/lib/assertion.js:65:17)
      at test/synchronize-test.js:57:39
      at searchCb (lib/mongoosastic.js:9:23566)
      at respond (node_modules/elasticsearch/src/lib/transport.js:277:9)
      at checkRespForFailure (node_modules/elasticsearch/src/lib/transport.js:219:7)
      at HttpConnector.<anonymous> (node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
      at IncomingMessage.wrapper (node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
      at endReadableNT (_stream_readable.js:903:12)

  8) Truncate esTruncate should be able to truncate all documents:

      Uncaught AssertionError: expected 1 to equal 0
      + expected - actual

      -1
      +0
      
      at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
      at Assertion.prop.value (node_modules/should/lib/assertion.js:65:17)
      at test/truncate-test.js:54:37
      at searchCb (lib/mongoosastic.js:9:23566)
      at respond (node_modules/elasticsearch/src/lib/transport.js:277:9)
      at checkRespForFailure (node_modules/elasticsearch/src/lib/transport.js:219:7)
      at HttpConnector.<anonymous> (node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
      at IncomingMessage.wrapper (node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
      at endReadableNT (_stream_readable.js:903:12)
```

**Comment by guumaster** [comment]
Maybe ES 2.0 takes longer to make documents available, as it is near-realtime, so in our tests we have several timeouts to ensure documents are indexed. 

Could you try to modify this values and re-run the tests? (I don't have ES 2.0 at hand right now)
```js 
// file: test/config.js
const INDEXING_TIMEOUT = process.env.INDEXING_TIMEOUT || 2000;
const BULK_ACTION_TIMEOUT = process.env.BULK_ACTION_TIMEOUT || 4000;
```

**Comment by JasonMore** [comment]
I get the same errors on ES2.0 with the default config, and when I set the config to the following values, even more tests fail, which seems odd:

```
const INDEXING_TIMEOUT = process.env.INDEXING_TIMEOUT || 12000;
const BULK_ACTION_TIMEOUT = process.env.BULK_ACTION_TIMEOUT || 14000;
```

```
1) Bulk mode should index all objects and support deletions too:
     Uncaught AssertionError: expected Object {
  hits: Array [
    Object {
      _id: '56460ad109866db11cddffd5',
      _index: 'book2s',
      _score: 1,
      _source: Object { _id: '56460ad109866db11cddffd5', title: 'ABABABA8' },
      _type: 'book2'
    },
    Object {
      _id: '56460ad109866db11cddffd2',
      _index: 'book2s',
      _score: 1,
      _source: Object { _id: '56460ad109866db11cddffd2', title: 'ABABABA5' },
      _type: 'book2'
    },
    Object {
      _id: '56460ad109866db11cddffdc',
      _index: 'book2s',
      _score: 1,
      _source: Object { _id: '56460ad109866db11cddffdc', title: 'ABABABA15' },
      _type: 'book2'
    },
    Object {
      _id: '56460ad109866db11cddffeb',
      _index: 'book2s',
      _score: 1,
      _source: Object { _id: '56460ad109866db11cddffeb', title: 'ABABABA30' },
      _type: 'book2'
    },
    Object {
      _id: '56460ad109866db11cddffce',
      _index: 'book2s',
      _score: 1,
      _source: Object { _id: '56460ad109866db11cddffce', title: 'ABABABA1' },
      _type: 'book2'
    },
    Object {
      _id: '56460ad109866db11cddffec',
      _index: 'book2s',
      _score: 1,
      _source: Object { _id: '56460ad109866db11cddffec', title: 'ABABABA31' },
      _type: 'book2'
    },
    Object {
      _id: '56460ad109866db11cddfff6',
      _index: 'book2s',
      _score: 1,
      _source: Object { _id: '56460ad109866db11cddfff6', title: 'ABABABA41' },
      _type: 'book2'
    },
    Object {
      _id: '56460ad109866db11cddffcf',
      _index: 'book2s',
      _score: 1,
      _source: Object { _id: '56460ad109866db11cddffcf', title: 'ABABABA2' },
      _type: 'book2'
    },
    Object {
      _id: '56460ad109866db11cddffd9',
      _index: 'book2s',
      _score: 1,
      _source: Object { _id: '56460ad109866db11cddffd9', title: 'ABABABA12' },
      _type: 'book2'
    },
    Object {
      _id: '56460ad109866db11cddffe8',
      _index: 'book2s',
      _score: 1,
      _source: Object { _id: '56460ad109866db11cddffe8', title: 'ABABABA27' },
      _type: 'book2'
    }
  ],
  max_score: 1,
  total: 51
} to have property total of 52 (got 51)
      at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
      at Assertion.prop.value [as property] (node_modules/should/lib/assertion.js:65:17)
      at test/bulk-test.js:64:51
      at searchCb (lib/mongoosastic.js:513:9)
      at respond (node_modules/elasticsearch/src/lib/transport.js:277:9)
      at checkRespForFailure (node_modules/elasticsearch/src/lib/transport.js:219:7)
      at HttpConnector.<anonymous> (node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
      at IncomingMessage.wrapper (node_modules/lodash/index.js:3095:19)
      at endReadableNT (_stream_readable.js:905:12)

  2) Custom Properties for Mapping should index with field "fullTitle":
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  3) Filter mode should index horror genre:
     Error: timeout of 7000ms exceeded. Ensure the done() callback is being called in this test.
  

  4) Filter mode should not index action genre:
     Uncaught TypeError: Cannot read property 'hits' of undefined
      at test/custom-mapping-test.js:53:16
      at searchCb (lib/mongoosastic.js:507:16)
      at respond (node_modules/elasticsearch/src/lib/transport.js:275:9)
      at sendReqWithConnection (node_modules/elasticsearch/src/lib/transport.js:190:7)
      at Object.utils.applyArgs (node_modules/elasticsearch/src/lib/utils.js:252:17)
      at wrapper (node_modules/lodash/index.js:3533:19)

  5) GeoTest should be able to find geo coordinates in the indexes:
     Uncaught TypeError: Cannot read property 'hits' of undefined
      at test/filtering-test.js:45:16
      at searchCb (lib/mongoosastic.js:507:16)
      at respond (node_modules/elasticsearch/src/lib/transport.js:275:9)
      at sendReqWithConnection (node_modules/elasticsearch/src/lib/transport.js:190:7)
      at Object.utils.applyArgs (node_modules/elasticsearch/src/lib/utils.js:252:17)
      at wrapper (node_modules/lodash/index.js:3533:19)

  6) GeoTest should be able to resync geo coordinates from the database:
     Error: timeout of 7000ms exceeded. Ensure the done() callback is being called in this test.
  

  7) Highlight search "before all" hook:
     Uncaught TypeError: Cannot read property 'hits' of undefined
      at test/filtering-test.js:63:16
      at searchCb (lib/mongoosastic.js:507:16)
      at respond (node_modules/elasticsearch/src/lib/transport.js:275:9)
      at sendReqWithConnection (node_modules/elasticsearch/src/lib/transport.js:190:7)
      at Object.utils.applyArgs (node_modules/elasticsearch/src/lib/utils.js:252:17)
      at wrapper (node_modules/lodash/index.js:3533:19)

  8) indexing Creating Index "after all" hook:

      Uncaught AssertionError: expected 1 to equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
      at Assertion.prop.value (node_modules/should/lib/assertion.js:65:17)
      at test/geo-test.js:109:31
      at searchCb (lib/mongoosastic.js:513:9)
      at respond (node_modules/elasticsearch/src/lib/transport.js:277:9)
      at checkRespForFailure (node_modules/elasticsearch/src/lib/transport.js:219:7)
      at HttpConnector.<anonymous> (node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
      at IncomingMessage.wrapper (node_modules/lodash/index.js:3095:19)
      at endReadableNT (_stream_readable.js:905:12)

  9) indexing Removing "before each" hook:

      Uncaught AssertionError: expected 1 to equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
      at Assertion.prop.value (node_modules/should/lib/assertion.js:65:17)
      at test/geo-test.js:135:37
      at searchCb (lib/mongoosastic.js:513:9)
      at respond (node_modules/elasticsearch/src/lib/transport.js:277:9)
      at checkRespForFailure (node_modules/elasticsearch/src/lib/transport.js:219:7)
      at HttpConnector.<anonymous> (node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
      at IncomingMessage.wrapper (node_modules/lodash/index.js:3095:19)
      at endReadableNT (_stream_readable.js:905:12)

  10) Highlight search Highlight without hydrating should return highlighted text on every hit result:
     Uncaught TypeError: Cannot read property 'hits' of undefined
      at test/highlight-features-test.js:80:12
      at searchCb (lib/mongoosastic.js:507:16)
      at respond (node_modules/elasticsearch/src/lib/transport.js:275:9)
      at sendReqWithConnection (node_modules/elasticsearch/src/lib/transport.js:190:7)
      at Object.utils.applyArgs (node_modules/elasticsearch/src/lib/utils.js:252:17)
      at wrapper (node_modules/lodash/index.js:3533:19)

  11) Highlight search Highlight hydrated results should return highlighted text on every resulting document:
     Uncaught TypeError: Cannot read property 'hits' of undefined
      at test/highlight-features-test.js:111:12
      at searchCb (lib/mongoosastic.js:507:16)
      at respond (node_modules/elasticsearch/src/lib/transport.js:275:9)
      at sendReqWithConnection (node_modules/elasticsearch/src/lib/transport.js:190:7)
      at Object.utils.applyArgs (node_modules/elasticsearch/src/lib/utils.js:252:17)
      at wrapper (node_modules/lodash/index.js:3533:19)

  12) indexing Default plugin should use the model's id as ES id:
     Uncaught TypeError: Cannot read property 'message' of undefined
      at test/index-test.js:129:22
      at respond (node_modules/elasticsearch/src/lib/transport.js:275:9)
      at checkRespForFailure (node_modules/elasticsearch/src/lib/transport.js:219:7)
      at HttpConnector.<anonymous> (node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
      at IncomingMessage.wrapper (node_modules/lodash/index.js:3095:19)
      at endReadableNT (_stream_readable.js:905:12)

  13) indexing Default plugin should be able to execute a simple query:

      Uncaught AssertionError: expected 0 to equal 1
      + expected - actual

      -0
      +1
      
      at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
      at Assertion.prop.value (node_modules/should/lib/assertion.js:65:17)
      at test/index-test.js:141:35
      at searchCb (lib/mongoosastic.js:513:9)
      at respond (node_modules/elasticsearch/src/lib/transport.js:277:9)
      at checkRespForFailure (node_modules/elasticsearch/src/lib/transport.js:219:7)
      at HttpConnector.<anonymous> (node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
      at IncomingMessage.wrapper (node_modules/lodash/index.js:3095:19)
      at endReadableNT (_stream_readable.js:905:12)

  14) indexing Default plugin should be able to execute a simple query:

      Uncaught AssertionError: expected 'Saying something I shouldnt' to equal 'I like Riak better'
      + expected - actual

      -Saying something I shouldnt
      +I like Riak better
      
      at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
      at Assertion.prop.value (node_modules/should/lib/assertion.js:65:17)
      at test/index-test.js:154:53
      at searchCb (lib/mongoosastic.js:513:9)
      at respond (node_modules/elasticsearch/src/lib/transport.js:277:9)
      at checkRespForFailure (node_modules/elasticsearch/src/lib/transport.js:219:7)
      at HttpConnector.<anonymous> (node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
      at IncomingMessage.wrapper (node_modules/lodash/index.js:3095:19)
      at endReadableNT (_stream_readable.js:905:12)

  15) indexing Default plugin should report errors:
     Uncaught AssertionError: expected '[query_parsing_exception] [_na] query malformed, no field after start_object, with: {"index":"tweets","line":1,"col":11}' to match /SearchPhaseExecutionException/
      at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
      at Assertion.prop.value [as match] (node_modules/should/lib/assertion.js:65:17)
      at test/index-test.js:197:28
      at searchCb (lib/mongoosastic.js:507:16)
      at respond (node_modules/elasticsearch/src/lib/transport.js:275:9)
      at checkRespForFailure (node_modules/elasticsearch/src/lib/transport.js:219:7)
      at HttpConnector.<anonymous> (node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
      at IncomingMessage.wrapper (node_modules/lodash/index.js:3095:19)
      at endReadableNT (_stream_readable.js:905:12)

  16) Suggesters Testing Suggest should index property name with type completion:

      Uncaught AssertionError: expected 'string' to equal 'completion'
      + expected - actual

      -string
      +completion
      
      at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
      at Assertion.prop.value (node_modules/should/lib/assertion.js:65:17)
      at test/suggesters-test.js:73:34
      at respond (node_modules/elasticsearch/src/lib/transport.js:277:9)
      at checkRespForFailure (node_modules/elasticsearch/src/lib/transport.js:219:7)
      at HttpConnector.<anonymous> (node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
      at IncomingMessage.wrapper (node_modules/lodash/index.js:3095:19)
      at endReadableNT (_stream_readable.js:905:12)

  17) Suggesters Testing Suggest should return suggestions after hits:
     Uncaught TypeError: Cannot read property 'should' of undefined
      at test/suggesters-test.js:91:12
      at searchCb (lib/mongoosastic.js:507:16)
      at respond (node_modules/elasticsearch/src/lib/transport.js:275:9)
      at checkRespForFailure (node_modules/elasticsearch/src/lib/transport.js:219:7)
      at HttpConnector.<anonymous> (node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
      at IncomingMessage.wrapper (node_modules/lodash/index.js:3095:19)
      at endReadableNT (_stream_readable.js:905:12)

  18) Transform mode should index with field "fullTitle":

      Uncaught AssertionError: expected 1 to equal 0
      + expected - actual

      -1
      +0
      
      at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
      at Assertion.prop.value (node_modules/should/lib/assertion.js:65:17)
      at test/index-test.js:237:35
      at searchCb (lib/mongoosastic.js:513:9)
      at respond (node_modules/elasticsearch/src/lib/transport.js:277:9)
      at checkRespForFailure (node_modules/elasticsearch/src/lib/transport.js:219:7)
      at HttpConnector.<anonymous> (node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
      at IncomingMessage.wrapper (node_modules/lodash/index.js:3095:19)
      at endReadableNT (_stream_readable.js:905:12)
```

**Comment by guumaster** [comment]
We need someone with more experience in ES 2.0 to look into this one.

**Comment by Alexandre-io** [comment]
- Truncate esTruncate should be able to truncate all documents:
Removed from native api after 1.7: cf. https://www.elastic.co/guide/en/elasticsearch/plugins/2.0/delete-by-query-plugin-reason.html

- Count should count a type:
Install plugin mapper-size (cf. https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_removed_features.html):
```
./bin/plugin install mapper-size
```

**Comment by Alexandre-io** [comment]
This commit (https://github.com/Alexandre-io/mongoosastic/commit/e420f85e57cc18ea04e4127eda3681924f0ae4b9) fix a lot of tests issues. I have to go deeper to check everything.

**Comment by Alexandre-io** [comment]
This branch https://github.com/Alexandre-io/mongoosastic/commits/feat-es2.0 fixes all issues.
I have to check backwards compatibility, but what do you think ?

**Comment by Alexandre-io** [comment]
#134 fix the issue
