### ISSUE TITLE
ObjectId not mapping correctly

### ISSUE THREAD

**Issue by jspizziri** [mongoosastic/mongoosastic#133]
The following schema fails to create a correct index in elasticsearch. It just fails silently due to the indexing the `company` ObjectId.

```js
var ClientSchema = new Schema({
  name: { type: String, required: 'Name is required.', es_indexed: true },
  info: String,
  address: { type: AddressSchema, es_indexed: true },
  email: { type: String, required: 'Email is required.', es_indexed: true },
  active: { type: Boolean, es_indexed: true },
  company: { 
    type : Schema.Types.ObjectId, 
    ref: 'Company', 
    required: true,
    es_indexed: true
  }
});
```

When I remove the indexing of the company field the indexes are built correctly.

**Comment by jspizziri** [comment]
Elasticsearch Error

```
[foobar][0] failed to execute bulk item (index) index {[foobar][client][5649d23371ab23595d413a70], source[{"name":"Client #1","address":{"_id":"5649d23371ab23595d413a6e","zip":"60178","state":"Illinois","city":"Sycamore","address_1":"303 E State St.","updatedAt":"2015-11-16T12:55:15.051Z","createdAt":"2015-11-16T12:55:15.051Z","__v":0},"email":"jspizziri@client.com","active":true,"company":"5649d23371ab23595d413a6f","_id":"5649d23371ab23595d413a70"}]}
org.elasticsearch.index.mapper.MapperParsingException: object mapping for [client] tried to parse as object, but got EOF, has a concrete value been provided to it?
	at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:467)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:515)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:462)
	at org.elasticsearch.index.shard.service.InternalIndexShard.prepareIndex(InternalIndexShard.java:384)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:418)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:160)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:556)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:426)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jspizziri** [comment]
Somehow a bad mapping for that schema had been created in Elasticsearch. Likely when I was doing a data model refactor, I deleted the mapping and when it was recreated it now works.

```
curl -XDELETE 'http://localhost:9200/foobar/client/_mapping'
```
