### ISSUE TITLE
Nothing is working

### ISSUE THREAD

**Issue by joshbedo** [mongoosastic/mongoosastic#154]
I've tried the examples and i've even created an index manually nothing is working for me. I'm getting an error when i try to create a mapping i also limited the fields down for the schema of my model to two so it's nothing complex. I'm using elasticsearch 2.1.1 and mongoose ^4.3.6 and mongoosastic ^3.6.0

**Comment by joshbedo** [comment]
Also seeing this output, "were connected" shows when mongoose creates a connection

```
were connected!
error creating mapping (you can safely ignore this)
{ [Error: No Living connections] message: 'No Living connections' }
worked
es-indexed
{ [Error: No Living connections] message: 'No Living connections' } undefined
```

**Comment by joshbedo** [comment]
here is some more info after adding some logging
```
➜  RoomThat git:(matching-ger) ✗ docker logs -f matching
Elasticsearch INFO: 2016-01-22T19:24:57Z
  Adding connection to http://127.0.0.1:9200/

Elasticsearch DEBUG: 2016-01-22T19:24:57Z
  starting request { method: 'HEAD', castExists: true, path: '/users', query: {} }


Creating a pool connected to 192.168.99.100:28015
Matching service listening on port 9876
Elasticsearch TRACE: 2016-01-22T19:25:00Z
  -> HEAD http://127.0.0.1:9200/users

  <- 0


Elasticsearch ERROR: 2016-01-22T19:25:00Z
  Error: Request error, retrying
  HEAD http://127.0.0.1:9200/users => connect ECONNREFUSED 127.0.0.1:9200
    at Log.error (/opt/services/matching/node_modules/elasticsearch/src/lib/log.js:225:56)
    at checkRespForFailure (/opt/services/matching/node_modules/elasticsearch/src/lib/transport.js:243:18)
    at HttpConnector.<anonymous> (/opt/services/matching/node_modules/elasticsearch/src/lib/connectors/http.js:153:7)
    at ClientRequest.wrapper (/opt/services/matching/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:441:9)
    at process._tickDomainCallback (node.js:396:17)


Elasticsearch TRACE: 2016-01-22T19:25:00Z
  -> HEAD http://127.0.0.1:9200/

  <- 0


Elasticsearch WARNING: 2016-01-22T19:25:00Z
  Unable to revive connection: http://127.0.0.1:9200/

Elasticsearch WARNING: 2016-01-22T19:25:00Z
  No living connections

error creating mapping (you can safely ignore this)
{ [Error: No Living connections] message: 'No Living connections' }
initialized matching: { deleted: 0,
  errors: 0,
  inserted: 0,
  replaced: 0,
  skipped: 0,
  unchanged: 1 }
were connected!
Elasticsearch DEBUG: 2016-01-22T19:25:01Z
  starting request { method: 'POST',
    path: '/users/user/56a2820c85edde0100b3c37f',
    body: {},
    query: {} }


worked
Elasticsearch TRACE: 2016-01-22T19:25:01Z
  -> HEAD http://127.0.0.1:9200/

  <- 0


Elasticsearch WARNING: 2016-01-22T19:25:01Z
  Unable to revive connection: http://127.0.0.1:9200/

Elasticsearch WARNING: 2016-01-22T19:25:01Z
  No living connections

es-indexed
{ [Error: No Living connections] message: 'No Living connections' } undefined
```

**Comment by joshbedo** [comment]
Got this working i found out it was an issue with connecting to my local ip from within a docker VM.
