### ISSUE TITLE
illegal_argument_exception each time i try to index ES 2.2

### ISSUE THREAD

**Issue by joshbedo** [mongoosastic/mongoosastic#165]
I keep getting this index error now that says i have a duplicate `_id`not sure how to fix this since its something automatically generated.. It wasn't happening a few days ago. Does anyone know how to fix this?

![](http://i.imgur.com/yThl7oM.jpg)

**Comment by nschloe** [comment]
Might be covered by https://github.com/mongoosastic/mongoosastic/pull/144.

**Comment by guumaster** [comment]
Could try again? #144 is merged now.

**Comment by joshbedo** [comment]
Thanks guys! Upgraded and confirm the fix on two separate docker services using mongoosastic.

**Comment by michelem09** [comment]
So do you think I should re-create the indexes after updating to ES 2.2.0 and Mongoosastic 4?

Because the searches work fine but I have a lot of ES warnings like this:

```
[2016-03-02 15:23:56,427][WARN ][cluster.action.shard     ] [esearch] [streetlib-dev3][2] received shard failed for [streetlib-dev3][2], node[6Hrw6K6mRKWbnl6L9YC8sw], [P], v[847], s[INITIALIZING], a[id=TK2N4o7yT-GCqkL_N_Rnew], unassigned_info[[reason=ALLOCATION_FAILED], at[2016-03-02T14:23:51.370Z], details[failed to update mappings, failure IllegalArgumentException[Field [_id] is defined twice in [catalog]]]], indexUUID [7EfzsOa_TwSuUBycDPyiqA], message [failed to update mappings], failure [IllegalArgumentException[Field [_id] is defined twice in [catalog]]]
java.lang.IllegalArgumentException: Field [_id] is defined twice in [catalog]
	at org.elasticsearch.index.mapper.MapperService.checkFieldUniqueness(MapperService.java:377)
	at org.elasticsearch.index.mapper.MapperService.checkMappersCompatibility(MapperService.java:385)
	at org.elasticsearch.index.mapper.MapperService.checkMappersCompatibility(MapperService.java:411)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:314)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:272)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.processMapping(IndicesClusterStateService.java:388)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyMappings(IndicesClusterStateService.java:348)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:164)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:600)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:762)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```
