### ISSUE TITLE
Issue with es_select destroying other mapping

### ISSUE THREAD

**Issue by nvartolomei** [mongoosastic/mongoosastic#196]
The issue is caused this line https://github.com/mongoosastic/mongoosastic/blob/master/lib/mapping-generator.js#L163

When having 2 models indexed in elastic search, but one is used in another as `ref`, and using `es_select` on it, it will remove "unused" fields from the referenced model. As a result this will generate another mapping for referenced model using the latest tree, which contains only fields specified in es_select, because all others were deleted by Line 163.

Is this clear or should I add an example?

**Comment by nvartolomei** [comment]
An easy way to solve this would be deep cloning the `tree` and `path` and not manipulating the one provided by mongoose.

**Comment by nodkz** [comment]
This PR broke such schema (with embedded schema as array):
```js
export const ArticleSchema = new Schema(
  {
    languages: {
      type: [LanguageSchema],
    },
});
```
with error
```
    TypeError: Cannot read property 'scope' of undefined

      at EmbeddedDocument.get [as id] (node_modules/mongoose/lib/document.js:1823:38)
      at assignValue (node_modules/lodash.clonedeep/index.js:789:24)
      at node_modules/lodash.clonedeep/index.js:897:5
      at arrayEach (node_modules/lodash.clonedeep/index.js:140:9)
      at baseClone (node_modules/lodash.clonedeep/index.js:891:3)
      at node_modules/lodash.clonedeep/index.js:897:30
      at arrayEach (node_modules/lodash.clonedeep/index.js:140:9)
      at baseClone (node_modules/lodash.clonedeep/index.js:891:3)
      at node_modules/lodash.clonedeep/index.js:897:30
      at arrayEach (node_modules/lodash.clonedeep/index.js:140:9)
      at baseClone (node_modules/lodash.clonedeep/index.js:891:3)
      at cloneDeep (node_modules/lodash.clonedeep/index.js:1399:10)
      at getCleanTree (node_modules/mongoosastic/lib/mapping-generator.js:135:11)
      at Generator.generateMapping (node_modules/mongoosastic/lib/mapping-generator.js:276:21)
      at getMapping (node_modules/mongoosastic/lib/mongoosastic.js:21:13)
      at Mongoosastic (node_modules/mongoosastic/lib/mongoosastic.js:207:17)
      at Schema.Object.<anonymous>.Schema.plugin (node_modules/mongoose/lib/schema.js:1139:3)
      at Object.<anonymous> (schema/article/index.js:241:10)
      at Object.<anonymous> (lib/graphql-compose-mongoosastic/__tests__/query-test.js:2:11)
      at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

DeepClone can not properly clone such schema.

**Comment by isayme** [comment]
@nodkz create a new issue please~

**Comment by nodkz** [comment]
@isayme done https://github.com/mongoosastic/mongoosastic/issues/306
