### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by anonrig** [mongoosastic/mongoosastic#231]
error: Cannot boot API RangeError: Maximum call stack size exceeded
    at getCleanTree (/Users/anonrig/Desktop/tusla/tusla-backend/node_modules/mongoosastic/lib/mapping-generator.js:169:19)
    at nestedSchema (/Users/anonrig/Desktop/tusla/tusla-backend/node_modules/mongoosastic/lib/mapping-generator.js:225:24)
    at getCleanTree (/Users/anonrig/Desktop/tusla/tusla-backend/node_modules/mongoosastic/lib/mapping-generator.js:146:9)
    at nestedSchema (/Users/anonrig/Desktop/tusla/tusla-backend/node_modules/mongoosastic/lib/mapping-generator.js:225:24)
    at getCleanTree (/Users/anonrig/Desktop/tusla/tusla-backend/node_modules/mongoosastic/lib/mapping-generator.js:146:9)
    at nestedSchema (/Users/anonrig/Desktop/tusla/tusla-backend/node_modules/mongoosastic/lib/mapping-generator.js:225:24)
    at getCleanTree (/Users/anonrig/Desktop/tusla/tusla-backend/node_modules/mongoosastic/lib/mapping-generator.js:146:9)
    at nestedSchema (/Users/anonrig/Desktop/tusla/tusla-backend/node_modules/mongoosastic/lib/mapping-generator.js:225:24)
    at getCleanTree (/Users/anonrig/Desktop/tusla/tusla-backend/node_modules/mongoosastic/lib/mapping-generator.js:146:9)
    at nestedSchema (/Users/anonrig/Desktop/tusla/tusla-backend/node_modules/mongoosastic/lib/mapping-generator.js:225:24)
    at getCleanTree (/Users/anonrig/Desktop/tusla/tusla-backend/node_modules/mongoosastic/lib/mapping-generator.js:146:9)
    at nestedSchema (/Users/anonrig/Desktop/tusla/tusla-backend/node_modules/mongoosastic/lib/mapping-generator.js:225:24)
    at getCleanTree (/Users/anonrig/Desktop/tusla/tusla-backend/node_modules/mongoosastic/lib/mapping-generator.js:146:9)
    at nestedSchema (/Users/anonrig/Desktop/tusla/tusla-backend/node_modules/mongoosastic/lib/mapping-generator.js:225:24)
    at getCleanTree (/Users/anonrig/Desktop/tusla/tusla-backend/node_modules/mongoosastic/lib/mapping-generator.js:146:9)
    at nestedSchema (/Users/anonrig/Desktop/tusla/tusla-backend/node_modules/mongoosastic/lib/mapping-generator.js:225:24)

**Comment by ermst4r** [comment]
Check the ulimit of the server e.g. or set the ulimit to  ulimit -n 2048

**Comment by isayme** [comment]
@anonrig please reopen the issue if you have more information~
