### ISSUE TITLE
mapping-generator fails with embedded schema as array

### ISSUE THREAD

**Issue by nodkz** [mongoosastic/mongoosastic#306]
Mapping-generator uses `lodash.deepClone` in https://github.com/mongoosastic/mongoosastic/blob/master/lib/mapping-generator.js#L135:
```js
  tree = cloneDeep(tree)
  paths = cloneDeep(paths)
```
Which fix [issue 196](https://github.com/mongoosastic/mongoosastic/issues/196) by [PR 197](https://github.com/mongoosastic/mongoosastic/pull/197)

And deepClone fails with embeddedSchema as array: 

```js
const LanguageSchema = new Schema(
  {
    ln: { type: String },
    sk: { type: String },
  },
  {  _id: false }
);

export const ArticleSchema = new Schema(
  {
    languages: {
      type: [LanguageSchema],
    },
});

ArticleSchema.plugin(mongoosastic);
```

With such error:
```
    TypeError: Cannot read property 'scope' of undefined

      at EmbeddedDocument.get [as id] (node_modules/mongoose/lib/document.js:1823:38)
      at assignValue (node_modules/lodash.clonedeep/index.js:789:24)
      at node_modules/lodash.clonedeep/index.js:897:5
      at arrayEach (node_modules/lodash.clonedeep/index.js:140:9)
      at baseClone (node_modules/lodash.clonedeep/index.js:891:3)
      at node_modules/lodash.clonedeep/index.js:897:30
      at arrayEach (node_modules/lodash.clonedeep/index.js:140:9)
      at baseClone (node_modules/lodash.clonedeep/index.js:891:3)
      at node_modules/lodash.clonedeep/index.js:897:30
      at arrayEach (node_modules/lodash.clonedeep/index.js:140:9)
      at baseClone (node_modules/lodash.clonedeep/index.js:891:3)
      at cloneDeep (node_modules/lodash.clonedeep/index.js:1399:10)
      at getCleanTree (node_modules/mongoosastic/lib/mapping-generator.js:135:11)
      at Generator.generateMapping (node_modules/mongoosastic/lib/mapping-generator.js:276:21)
      at getMapping (node_modules/mongoosastic/lib/mongoosastic.js:21:13)
      at Mongoosastic (node_modules/mongoosastic/lib/mongoosastic.js:207:17)
      at Schema.Object.<anonymous>.Schema.plugin (node_modules/mongoose/lib/schema.js:1139:3)
      at Object.<anonymous> (schema/article/index.js:241:10)
      at Object.<anonymous> (lib/graphql-compose-mongoosastic/__tests__/query-test.js:2:11)
      at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

So mongoose schema can not be cloned by lodash.deepClone. DeepClone can not properly clone such schema cause called magic `get` method of mongose [document.get](https://github.com/Automattic/mongoose/blob/master/lib/document.js#L1762):
`$__` is not initialized for arrays.

Maybe a problem should be fixed there, but Mongoose does not expose its paths for cloning. So I think, that cloning should be solved in this lib.

**Comment by isayme** [comment]
@nodkz I tried your schema, but no error occur.

what is your node version, mongoose version?

and could show full example code?

**Comment by nodkz** [comment]
Ooops something strange. 
With dev build all works perfectly. But when I run Jest tests this error occurs.
So I think that this problem somewhere inside my test environment.

I'm so sorry. Please excuse for troubling
