### ISSUE TITLE
Schema Validation Error triggers Stream Error callback

### ISSUE THREAD

**Issue by sedouard** [mongoosastic/mongoosastic#353]
## Your Environments
- mongoosastic version: 4.3.0
- node version: 6.1.0
- mongoose version: 4.7.5
- elasticsearch version: 2.3.3

## Expected Behavior

```js
let stream = model.synchronized;
stream.on('data', (err, doc) => {
    if (err) {
       // we expect to get an error here if there is a schema validation error
    }
})
stream.in('error', (err) => {
  // we expect to get an err here if something not document-specific
  // causes an error and stops the entire index sync
})
stream.in('close', (err) => {
  // we expect to get a close event here even if a schema was invalid
})
```

## Actual Behavior
```js
let stream = model.synchronized;
stream.on('data', (err, doc) => {
    if (err) {
       // we don't get any document validation error here
    }
})
stream.in('error', (err) => {
  // we get an error here for invalid documents in the database that
  // do not conform to schema. even though the indexing continues.
})
stream.in('close', (err) => {
  // never called :-(
})
```
## Error Stack

```
Failed to index with error:  { ValidationError: Cast to number failed for value "1000/hr" at path "legal.sow.payment.rate"
    at MongooseError.ValidationError (node_modules/mongoose/lib/error/validation.js:23:11)
    at model.Document.invalidate (node_modules/mongoose/lib/document.js:1486:32)
    at _init (node_modules/mongoose/lib/document.js:371:18)
    at init (node_modules/mongoose/lib/document.js:347:7)
    at _init (node_modules/mongoose/lib/document.js:362:7)
    at init (node_modules/mongoose/lib/document.js:347:7)
    at _init (node_modules/mongoose/lib/document.js:362:7)
    at init (node_modules/mongoose/lib/document.js:347:7)
    at _init (node_modules/mongoose/lib/document.js:362:7)
    at init (node_modules/mongoose/lib/document.js:347:7)
    at model.Document.init (node_modules/mongoose/lib/document.js:312:3)
    at _create (node_modules/mongoose/lib/querycursor.js:306:12)
    at node_modules/mongoose/lib/querycursor.js:271:17
    at handleCallback (node_modules/mongodb/lib/utils.js:95:56)
    at node_modules/mongodb/lib/cursor.js:674:5
    at handleCallback (node_modules/mongodb-core/lib/cursor.js:171:5)```

**Comment by sedouard** [comment]
The error has to do with this line:

https://github.com/mongoosastic/mongoosastic/blob/master/lib/mongoosastic.js#L533

The stream continues, even though the entire synchonization error event is called even though the stream resumes.

We have no idea on our side when we're done if we ignore this callback since we never get a `close` event when this occurs.

**Comment by sedouard** [comment]
PR #354 addresses the `close` event not being called, which is enough to unblock us.

I believe changing the `data` event to emit for document-specific errors would be a breaking change so I did not include that.
