### ISSUE TITLE
Error in mapping creation of geo_point with es_indexed

### ISSUE THREAD

**Issue by markusv** [mongoosastic/mongoosastic#412]
I have an issue when setting geo_point to be indexed. The mapping creation fails with error

Error: [mapper_parsing_exception] Mapping definition for [geo_cords] has unsupported parameters:  [lat_lon : true]

here is my field:

```
geo_cords: { 
    geo_point: {
      type: String,
      es_type: 'geo_point',
      es_lat_lon: true,
      es_indexed: true
    },
    lat: { type: Number },
    lon: { type: Number },
  }
```

without es_indexed the mapping creation succeeds, but then the field does not get indexed in elastic search. Please help!

## Your Environments
- mongoosastic version:4.3.0
- node version: 8.5.0
- mongoose version: 4.11.7
- elasticsearch version: 5.6.1

## Expected Behavior
Mapping should not fail and geo_point should be indexed in elastic search

## Actual Behavior
Mapping failes

## Error Stack
```
mapping creation failed { Error: [mapper_parsing_exception] Mapping definition for [geo_cords] has unsupported parameters:  [lat_lon : true]
    at respond (/Users/markusvoss/Prosjekter/finntrening/api/node_modules/elasticsearch/src/lib/transport.js:289:15)
    at checkRespForFailure (/Users/markusvoss/Prosjekter/finntrening/api/node_modules/elasticsearch/src/lib/transport.js:248:7)
    at HttpConnector.<anonymous> (/Users/markusvoss/Prosjekter/finntrening/api/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
    at IncomingMessage.wrapper (/Users/markusvoss/Prosjekter/finntrening/api/node_modules/lodash/lodash.js:4968:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  status: 400,
  displayName: 'BadRequest',
  message: '[mapper_parsing_exception] Mapping definition for [geo_cords] has unsupported parameters:  [lat_lon : true]',
  path: '/studios/_mapping/studio',
  query: {},
  body: '{"studio":{"properties":{"name":{"type":"string"},"geo_cords":{"type":"geo_point","lat_lon":true}}}}',
  statusCode: 400,
  response: '{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Mapping definition for [geo_cords] has unsupported parameters:  [lat_lon : true]"}],"type":"mapper_parsing_exception","reason":"Mapping definition for [geo_cords] has unsupported parameters:  [lat_lon : true]"},"status":400}',
  toString: [Function],
  toJSON: [Function] } { error: 
   { root_cause: [ [Object] ],
     type: 'mapper_parsing_exception',
     reason: 'Mapping definition for [geo_cords] has unsupported parameters:  [lat_lon : true]' },
  status: 400 }
```

**Comment by VunterSlaush** [comment]
:+1:
