### ISSUE TITLE
Deep cloning a mongoose model with arrays inside doesn't work

### ISSUE THREAD

**Issue by MumblesNZ** [mongoosastic/mongoosastic#444]
Hello,

When trying initiate mongoosastic:

`               const newSchema = new mongoose.Schema(fields, { timestamps: true });
                newSchema.plugin(mongoosastic);
                return this.connection.model<any>(formTypeId, newSchema);
`
I get an exception `[ExceptionsHandler] Class constructor CoreMongooseArray cannot be invoked without 'new'`

I've been reading this issue  https://github.com/Automattic/mongoose/issues/6507 which was the same behaviour as what I'm getting with mongoosastic, and changing the lodash.cloneDeep version which is used in mapping-generator.js to 4.17.4 seems to solve it for me as well. cloneDeep as a standalone repo seems to not have been updated since 4.5.0. 

Do other people have this issue and have a solution? Happy to create a PR changing the lodash.cloneDeep 4.5.0 dependency to lodash 4.17.4 is the best solution? 

Thanks in advance. 

## Your Environments
- mongoosastic version: 4.4.1
- node version: v8.11.3
- mongoose version: 5.2.7
- elasticsearch version: 13.3.0

## Expected Behavior

When initializing mongoosastic it shouldn't throw an error. 

## Actual Behavior

Error is being thrown as below.

## Error Stack

`[Nest] 36092   - 2018-8-10 11:50:56   [ExceptionsHandler] Class constructor CoreMongooseArray cannot be invoked without 'new'
TypeError: Class constructor CoreMongooseArray cannot be invoked without 'new'
    at initCloneArray (C:\GIT\forms-ms\node_modules\lodash.clonedeep\index.js:1235:22)
    at baseClone (C:\GIT\forms-ms\node_modules\lodash.clonedeep\index.js:854:14)
    at C:\GIT\forms-ms\node_modules\lodash.clonedeep\index.js:897:30
    at arrayEach (C:\GIT\forms-ms\node_modules\lodash.clonedeep\index.js:140:9)
    at baseClone (C:\GIT\forms-ms\node_modules\lodash.clonedeep\index.js:891:3)
    at C:\GIT\forms-ms\node_modules\lodash.clonedeep\index.js:897:30
    at arrayEach (C:\GIT\forms-ms\node_modules\lodash.clonedeep\index.js:140:9)
    at baseClone (C:\GIT\forms-ms\node_modules\lodash.clonedeep\index.js:891:3)
    at C:\GIT\forms-ms\node_modules\lodash.clonedeep\index.js:897:30
    at arrayEach (C:\GIT\forms-ms\node_modules\lodash.clonedeep\index.js:140:9)
    at baseClone (C:\GIT\forms-ms\node_modules\lodash.clonedeep\index.js:891:3)
    at C:\GIT\forms-ms\node_modules\lodash.clonedeep\index.js:897:30
    at arrayEach (C:\GIT\forms-ms\node_modules\lodash.clonedeep\index.js:140:9)
    at baseClone (C:\GIT\forms-ms\node_modules\lodash.clonedeep\index.js:891:3)
    at cloneDeep (C:\GIT\forms-ms\node_modules\lodash.clonedeep\index.js:1399:10)
    at getCleanTree (C:\GIT\forms-ms\node_modules\mongoosastic\lib\mapping-generator.js:135:11)`

**Comment by MumblesNZ** [comment]
My solution was to migrate to this library: https://github.com/jbdemonte/mongoose-elasticsearch-xp.
