### ISSUE TITLE
Hydrate Error when no data in elastic

### ISSUE THREAD

**Issue by ankit307** [mongoosastic/mongoosastic#530]
While using hydrate with a model having no data in elastic get Error:
/usr/src/backend/node_modules/mongoosastic/lib/mongoosastic.js:113
  const ids = results.hits.map((result, idx) => {
                      ^

TypeError: Cannot read property 'hits' of undefined
    at hydrate (/usr/src/backend/node_modules/mongoosastic/lib/mongoosastic.js:113:23)
    at esClient.search (/usr/src/backend/node_modules/mongoosastic/lib/mongoosastic.js:691:9)
    at f (/usr/src/backend/node_modules/once/once.js:25:25)
    at IncomingMessage.response.on (/usr/src/backend/node_modules/@elastic/elasticsearch/lib/Transport.js:305:11)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

## Your Environments
- mongoosastic version: 4.4.1
- node version: 10
- mongoose version: 5.9.3
- elasticsearch version: 7.4.1

## Expected Behavior
I used hydrate=true so it should return the ids map or blank array.

## Actual Behavior
Getting above error and code breaks

## Error Stack
  const ids = results.hits.map((result, idx) => {
                      ^

TypeError: Cannot read property 'hits' of undefined
    at hydrate (/usr/src/backend/node_modules/mongoosastic/lib/mongoosastic.js:113:23)
    at esClient.search (/usr/src/backend/node_modules/mongoosastic/lib/mongoosastic.js:691:9)
    at f (/usr/src/backend/node_modules/once/once.js:25:25)
    at IncomingMessage.response.on (/usr/src/backend/node_modules/@elastic/elasticsearch/lib/Transport.js:305:11)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by ankit307** [comment]
For more context, we have to add body key after results for extracting hit data.
