### ISSUE TITLE
_doc.populate is not a function

### ISSUE THREAD

**Issue by BhupenPal** [mongoosastic/mongoosastic#560]
## Your Environments
- "mongoosastic": "^4.6.0",
- node version: v15
- "mongoose": "^5.11.12"
- "@elastic/elasticsearch": "^7.12.0",

## Expected Behavior
While reading and updating the document with findOneAndUpdate, it should return the document and update the changes in MongoDB, and if there is any change in the indexed data the same should be updated on Elastic Search. But instead, it is throwing an error.

## Actual Behavior
Throws an error on reading and updating documents using findOneAndUpdate (_doc.populate is not a function)

## Error Stack
[server] TypeError: _doc.populate is not a function
[server]     at /Users/bhupen/Drive/Projects/Tealfeed/backend/node_modules/mongoosastic/lib/mongoosastic.js:263:16
[server]     at Array.forEach (<anonymous>)
[server]     at model.Query.postSave (/Users/bhupen/Drive/Projects/Tealfeed/backend/node_modules/mongoosastic/lib/mongoosastic.js:263:18)
[server]     at next (/Users/bhupen/Drive/Projects/Tealfeed/backend/node_modules/kareem/index.js:199:31)
[server]     at Kareem.execPost (/Users/bhupen/Drive/Projects/Tealfeed/backend/node_modules/kareem/index.js:218:3)
[server]     at _cb (/Users/bhupen/Drive/Projects/Tealfeed/backend/node_modules/kareem/index.js:308:15)
[server]     at _completeOneLean (/Users/bhupen/Drive/Projects/Tealfeed/backend/node_modules/mongoose/lib/query.js:3620:10)
[server]     at /Users/bhupen/Drive/Projects/Tealfeed/backend/node_modules/mongoose/lib/query.js:2083:7
[server]     at /Users/bhupen/Drive/Projects/Tealfeed/backend/node_modules/mongoose/lib/model.js:4863:16
[server]     at /Users/bhupen/Drive/Projects/Tealfeed/backend/node_modules/mongoose/lib/helpers/promiseOrCallback.js:24:16
[server]     at /Users/bhupen/Drive/Projects/Tealfeed/backend/node_modules/mongoose/lib/model.js:4886:21
[server]     at next (/Users/bhupen/Drive/Projects/Tealfeed/backend/node_modules/mongoose/lib/model.js:4320:5)
[server]     at _done (/Users/bhupen/Drive/Projects/Tealfeed/backend/node_modules/mongoose/lib/model.js:4468:5)
[server]     at _next (/Users/bhupen/Drive/Projects/Tealfeed/backend/node_modules/mongoose/lib/model.js:4451:7)
[server]     at /Users/bhupen/Drive/Projects/Tealfeed/backend/node_modules/mongoose/lib/model.js:4529:5
[server]     at /Users/bhupen/Drive/Projects/Tealfeed/backend/node_modules/mongoose/lib/model.js:4863:16

**Comment by BhupenPal** [comment]
Never mind, I was using lean: true while querying with findOneAndUpdate which basically just returns a POJO (Plain Old JavaScript Object) and MongoDB operations like .populate() .index() can't be run on them. Took around an hour to figure it out after trying to debug the package myself.
