### ISSUE TITLE
Can't deploy to Heroku due to "Error: Unable to load PFX certificate" from mongoosastic

### ISSUE THREAD

**Issue by xindixu** [mongoosastic/mongoosastic#569]
I deployed my Node.js app with React frontend to Heroku, with Bonsai add-on. The error " Error: Unable to load PFX certificate" thrown from mongoosastic is preventing the app to run. Any help will be appreciated.

## Your Environments
- mongoosastic version: 4.6.0
- node version: 16.9.1
- mongoose version: 5.13.9
- elasticsearch version: 16.7.2

## Expected Behavior
App should run.

## Actual Behavior
Working fine locally. App built and deployed to Heroku but it won't run. "Error: Unable to load PFX certificate" is thrown when app starts.

## Error Stack
Heroku log
```
2021-09-20T03:08:53.841609+00:00 app[web.1]: $ node index.js
2021-09-20T03:08:56.236661+00:00 app[web.1]: node:internal/tls/secure-context:278
2021-09-20T03:08:56.236671+00:00 app[web.1]:       context.loadPKCS12(toBuf(pfx));
2021-09-20T03:08:56.236671+00:00 app[web.1]:               ^
2021-09-20T03:08:56.236672+00:00 app[web.1]: 
2021-09-20T03:08:56.236672+00:00 app[web.1]: Error: Unable to load PFX certificate
2021-09-20T03:08:56.236673+00:00 app[web.1]:     at configSecureContext (node:internal/tls/secure-context:278:15)
2021-09-20T03:08:56.236673+00:00 app[web.1]:     at Object.createSecureContext (node:_tls_common:116:3)
2021-09-20T03:08:56.236674+00:00 app[web.1]:     at Object.connect (node:_tls_wrap:1621:48)
2021-09-20T03:08:56.236674+00:00 app[web.1]:     at HttpsAgent.createConnection (node:https:143:22)
2021-09-20T03:08:56.236674+00:00 app[web.1]:     at HttpsAgent.createSocket (/app/backend/node_modules/agentkeepalive/lib/_http_agent.js:265:26)
2021-09-20T03:08:56.236675+00:00 app[web.1]:     at HttpsAgent.createSocket (/app/backend/node_modules/agentkeepalive/lib/agent.js:77:11)
2021-09-20T03:08:56.236675+00:00 app[web.1]:     at HttpsAgent.addRequest (/app/backend/node_modules/agentkeepalive/lib/_http_agent.js:239:10)
2021-09-20T03:08:56.236676+00:00 app[web.1]:     at new ClientRequest (node:_http_client:305:16)
2021-09-20T03:08:56.236676+00:00 app[web.1]:     at Proxy.request (node:https:353:10)
2021-09-20T03:08:56.236679+00:00 app[web.1]:     at HttpConnector.request (/app/backend/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/connectors/http.js:182:23)
2021-09-20T03:08:56.236680+00:00 app[web.1]:     at sendReqWithConnection (/app/backend/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/transport.js:263:35)
2021-09-20T03:08:56.236680+00:00 app[web.1]:     at Object.utils.applyArgs (/app/backend/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/utils.js:188:19)
2021-09-20T03:08:56.236681+00:00 app[web.1]:     at wrapper (/app/backend/node_modules/lodash/lodash.js:5255:19)
2021-09-20T03:08:56.236681+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:78:11) {
2021-09-20T03:08:56.236681+00:00 app[web.1]:   code: 'ERR_CRYPTO_OPERATION_FAILED'
2021-09-20T03:08:56.236682+00:00 app[web.1]: }
2021-09-20T03:45:14.176573+00:00 app[web.1]: error Command failed with exit code 1.
2021-09-20T03:45:14.176675+00:00 app[web.1]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by guumaster** [comment]
Thanks for reporting it. Since this is related to ElasticSearch, I'm closing this.
