### ISSUE TITLE
From and Size for Pagination 

### ISSUE THREAD

**Issue by aalireza439** [mongoosastic/mongoosastic#77]
how i can use form and size in mongoosastic ?
 i try this , but its not working . 

```
music.search( {query_string:{ query:term }}, { hydrate:true },{from:0},{size:20}, function(err,results)
```

error:
```
/home/app/node_modules/mongoosastic/lib/mongoosastic.js:256
        cb(null, res);
        ^
TypeError: object is not a function
    at /home/app/node_modules/mongoosastic/lib/mongoosastic.js:256:9
    at respond (/home/app/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/transport.js:256:9)
    at checkRespForFailure (/home/app/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/transport.js:203:7)
    at HttpConnector.<anonymous> (/home/app/node_modules/mongoosastic/node_modules/elasticsearch/src/lib/connectors/http.js:156:7)
    at IncomingMessage.wrapper (/home/app/node_modules/lodash/index.js:3057:19)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```
Any thoughts? Thanks in advance!

**Comment by guumaster** [comment]
Try it this way: 

```
music.search( {query_string:{ query:term }}, { from:0, size:20, hydrate:true }, function(err,results)
```
