### ISSUE TITLE
Error when using complex sort object

### ISSUE THREAD

**Issue by fouadh** [mongoosastic/mongoosastic#78]
Hi,

First, thank you for your plugin, it is very useful !

When using a complex sort object to execute a query, there is an exception.

Here is a test to reproduce it from _search-features-test.js_:

```javascript
 it('should be able to sort by name in descending order', function(done) {
       Bond.search({
         match_all: {}
       }, {
         sort: [{
           name: { order: 'desc' }
         }]
       }, function(err, res) {
         var expected = ['Legal', 'Construction', 'Commercial', 'Bail'];
         res.hits.total.should.eql(4);
         res.hits.hits.forEach(function(bond, index) {
           expected[index].should.eql(bond._source.name);
         });
         done();
       });
});
```
The error is:

```
Message:
     Cannot read property 'hits' of undefined
 Details:
     domain: [object Object]
     domainThrown: true
 Stack:
 TypeError: Cannot read property 'hits' of undefined
     at /dev/sandbox/mongoosastic/test/search-features-test.js:88:12
     at /dev/sandbox/mongoosastic/lib/mongoosastic.js:250:16
     at respond (/dev/sandbox/mongoosastic/node_modules/elasticsearch/src/lib/transport.js:254:9)
     at checkRespForFailure (/dev/sandbox/mongoosastic/node_modules/elasticsearch/src/lib/transport.js:203:7)
     at HttpConnector.<anonymous> (/dev/sandbox/mongoosastic/node_modules/elasticsearch/src/lib/connectors/http.js:156:7)
     at IncomingMessage.wrapper (/dev/sandbox/mongoosastic/node_modules/elasticsearch/node_modules/lodash/index.js:3181:19)
     at IncomingMessage.emit (events.js:129:20)
     at _stream_readable.js:908:16
     at process._tickDomainCallback (node.js:381:11)
```

A possible workaround is the one below but I am not sure if this is a good solution: the sort option is placed into the body of the ES query when it is not a string (see my comments in the code).

```javascript
   schema.statics.search = function(query, options, cb) {
     if (arguments.length === 2) {
       cb = arguments[1];
       options = {};
     }
 
     options.hydrateOptions = options.hydrateOptions || defaultHydrateOptions || {};
 
     if (query === null)
       query = undefined;
 
     var _this = this,
       sort = options.sort,  // i add this variable here
       esQuery = {
         body: {
           query: query
         },
         index: options.index || indexName,
         type: options.type || typeName
       };
     if (options.highlight) {
       esQuery.body.highlight = options.highlight;
     }
 
     // put the sort option in the body of the query when this is no a string
     if (sort && typeof (sort) !== 'string') {
       esQuery.body.sort = options.sort;
     }
 
     Object.keys(options).forEach(function(opt) {
       // keep the old way when the sort is a string
       if (!opt.match(/hydrate/) && (!opt.match(/sort/) || typeof (sort) === 'string') && options.hasOwnProperty(opt))
         esQuery[opt] = options[opt];
     });
```

**Comment by guumaster** [comment]
This is related to a feature/error of the underlaying elasticsearch-js, related to [this issue](https://github.com/elastic/elasticsearch-js/issues/148). We should fix and test the sort option parameter.

**Comment by guumaster** [comment]
There is a new commit that fix this problem.

**Comment by Jeyasribakaran** [comment]
mongoosastic plugin did't support in elasticsearch 7.2
